### ISSUE TITLE
Exception thrown in Intellij 13.1.3

### ISSUE THREAD

**Issue by passiondroid** [pedrovgs/AndroidWiFiADB#33]
NoSuchMethodError: org.jetbrains.android.sdk.AndroidSdkUtils.getAdb(Lcom/intellij/openapi/project/Project;)Ljava/io/File;: org.jetbrains.android.sdk.AndroidSdkUtils.getAdb(Lcom/intellij/openapi/project/Project;)Ljava/io/File;

**Comment by pedrovgs** [comment]
Hi @passiondroid can you try with the new version I've released today? Version 2.0

**Comment by passiondroid** [comment]
@pedrovgs - Sorry for testing it too late but same issue still occurs.

**Comment by pedrovgs** [comment]
@passiondroid can you check if the same exception is thrown in the latest IntelliJ/AndroidStudio version?
